overwrite: true
schema: 'http://localhost:3000/api'
documents: './**/*.graphql'
generates:
  generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
